# https://upptime.js.org/docs/configuration

owner: wanderer-moe # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: wanderer.moe
    url: https://wanderer.moe
    assignees:
      - dromzeh
  - name: api
    url: https://api.wanderer.moe
    assignees:
      - dromzeh
  - name: cdn
    url: https://cdn.wanderer.moe
    assignees:
      - dromzeh
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # theme: dark
  # https://upptime.js.org/docs/configuration/#theme ?????????
  themeUrl: https://cdn.statically.io/gh/wanderer-moe/status/master/assets/dark-theme.css # see upptime/upptime/issues/468
  cname: status.wanderer.moe
  logoUrl: https://wanderer.moe/favicon.png
  name: status.wanderer.moe
  introTitle: "wanderer.moe Status Page"
  introMessage: This page consistently monitors [wanderer.moe](https://wanderer.moe) & its other components to check for any downtime. All outages are reported here and on the [discord server](https://discord.wanderer.moe/).
  navbar:
    - title: Status
      href: /
