# https://upptime.js.org/docs/configuration

owner: wanderer-moe # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: wanderer.moe
    url: https://wanderer.moe
    assignees:
      - dromzeh
  - name: api
    url: https://api.wanderer.moe
    assignees:
      - dromzeh
  - name: cdn
    url: https://cdn.wanderer.moe
    assignees:
      - dromzeh
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  theme: https://status.wanderer.moe/dark-theme.css
  cname: status.wanderer.moe
  logoUrl: https://wanderer.moe/favicon.png
  name: status.wanderer.moe
  introTitle: "wanderer.moe Status Page"
  introMessage: This page consistently monitors [wanderer.moe](https://wanderer.moe) & its other components to check for any downtime. All outages are reported here and on the [discord server](https://discord.wanderer.moe/).
  navbar:
    - title: Status
      href: /

commitMessages:
  readmeContent: "chore: update summary in `README` [skip ci] [upptime]"
  summaryJson: "chore: update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: "chore: update graphs [skip ci] [upptime]"
