# Change these first
owner: wanderer-moe # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: wanderer.moe
    url: https://wanderer.moe
    assignees:
      - dromzeh
  - name: api
    url: https://api.wanderer.moe
    assignees:
      - dromzeh
  - name: cdn
    url: https://cdn.wanderer.moe
    assignees:
      - dromzeh
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wanderer.moe
  # baseUrl: /your-repo-name
  logoUrl: https://wanderer.moe/favicon.png
  name: status.wanderer.moe
  introTitle: "wanderer.moe Status Page"
  introMessage: This page monitors [wanderer.moe](https://wanderer.moe) and its other components to check for any downtime. All outages & updates can be recorded both here and on the [discord server](https://discord.wanderer.moe/).
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
